# Generated by Django 5.0.2 on 2024-03-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='subject',
        ),
    ]
